inicio
    inteiro n [5], m [5],f [5], c,d
    para c de 0 até 4 passo 1
        ler n [c]
    proximo
        para c de 0 até 4 passo 1
            ler m [c]
        proximo
            para c de 0 até 4 passo 1
                f [c] <- n [c] + m [c]
                proximo
                para c de 0 até 4 passo 1
                    escrever f [c]
                    proximo
                    fim
                    
            
           
           
