inicio
    inteiro z,x,c,v,b,maior
    ler z,x,c,v,b
        se z > maior então
        maior <- z
        fimse
        se x > maior então
        maior <- x
        fimse
        se c > maior então
        maior <- c
        fimse
        se v > maior então
        maior <- v
        fimse
        se b > maior então
        maior <- b
        fimse
        escrever "\no seu maior numero foi: ",maior
fim

        