inicio
    inteiro matriz [ 4 ] [ 4 ]
    inteiro linha , coluna , numero
    escrever "Preenchendo a matriz... \n"
    para linha de 0 ate 3 passo 1
        para coluna de 0 ate 3 passo 1
            matriz [linha] [coluna] <- aleatorio * 51
        proximo
    proximo
    escrever "Matriz gerada: \n"
    para linha de 0 ate 3 passo 1
        para coluna de 0 ate 3 passo 1
            escrever matriz [ linha ] [ coluna ] , " - "
        proximo
        escrever "\n"
    proximo
fim


