inicio
    inteiro c
    faz
    escrever "\ndigite o código, ou 0 para sair\n"
    ler c
    escolhe c
    caso 1:
        escrever "gerente"
    caso 2:
        escrever "supervisor"
    caso 3:
        escrever "contador"
    caso 4:
        escrever "digitador"
    caso 5:
        escrever "auxiliar administrativo"
    caso 0:
        escrever "\nfinalizando"
    defeito:
        escrever "\ncódigo invalido"
   
    fimescolhe
    enquanto c =/= 0
fim

    
